// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Sistema_de_Matricula;
using System;

namespace Sistema_de_Matricula.Migrations
{
    [DbContext(typeof(SistemaMatriculaContext))]
    [Migration("20171018185832_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sistema_de_Matricula.Models.Aluno", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CursoID");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome");

                    b.Property<string>("Sexo");

                    b.HasKey("ID");

                    b.HasIndex("CursoID");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Sistema_de_Matricula.Models.AlunosTurma", b =>
                {
                    b.Property<int>("TurmaID");

                    b.Property<int>("AlunoID");

                    b.HasKey("TurmaID", "AlunoID");

                    b.HasIndex("AlunoID");

                    b.ToTable("Sala");
                });

            modelBuilder.Entity("Sistema_de_Matricula.Models.Curso", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("ID");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Sistema_de_Matricula.Models.Materia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CursoID");

                    b.Property<string>("Nome");

                    b.HasKey("ID");

                    b.HasIndex("CursoID");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("Sistema_de_Matricula.Models.Professor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GrauAcademico");

                    b.Property<string>("Nome");

                    b.Property<int>("Registro");

                    b.Property<string>("Sexo");

                    b.HasKey("ID");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("Sistema_de_Matricula.Models.Turma", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CursoID");

                    b.Property<int?>("MateriaID");

                    b.Property<string>("Nome");

                    b.Property<int>("ProfessorID");

                    b.HasKey("ID");

                    b.HasIndex("MateriaID");

                    b.HasIndex("ProfessorID");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Sistema_de_Matricula.Models.Aluno", b =>
                {
                    b.HasOne("Sistema_de_Matricula.Models.Curso", "Cursos")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema_de_Matricula.Models.AlunosTurma", b =>
                {
                    b.HasOne("Sistema_de_Matricula.Models.Aluno", "Aluno")
                        .WithMany("AlunosTurmas")
                        .HasForeignKey("AlunoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sistema_de_Matricula.Models.Turma", "Turma")
                        .WithMany("AlunosTurmas")
                        .HasForeignKey("TurmaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema_de_Matricula.Models.Materia", b =>
                {
                    b.HasOne("Sistema_de_Matricula.Models.Curso", "Cursos")
                        .WithMany("Materias")
                        .HasForeignKey("CursoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema_de_Matricula.Models.Turma", b =>
                {
                    b.HasOne("Sistema_de_Matricula.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaID");

                    b.HasOne("Sistema_de_Matricula.Models.Professor", "Professor")
                        .WithMany("Turmas")
                        .HasForeignKey("ProfessorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
